# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9cb2fc03578bab0f1dbde0346b4816d079bd345be23a2689f2a7cd296270446e11e7bd0a53673d303b9cfe104873c9b79df2eba3e8cdcd41894ce6b4564b307a

test:
  secret_key_base: 58497efd3db54ecf075bed05ff426822046641b07e31a6f1e97de3e2de3d1ab1ced67bbbcadc0f7b99599c6866ce674fe9c841907f19220294b544c6baeef58d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
